name: sofija_tracker
description: Sofija Tracker - praÄ‡enje hranjenja, pelena i stolice (SR/EN), profili, podsetnici, grafikoni.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # IDs / settings
  uuid: ^4.4.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2

  # Notifications & time
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

  # Charts
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Codegen (Hive)
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

  # App icon + splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/app_icon.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/app_icon.png
  android: true
  ios: false
  android_12:
    color: "#FFFFFF"
    image: assets/icon/app_icon.png
